### ISSUE TITLE
Feature Request: Add an Endpoint to Retrieve Kafka Connection Details

### ISSUE THREAD

**Issue by Andreufb** [sci-ndp/pop#10]
Currently, the Kafka connection details (port, host, prefix, and maximum streams) are hardcoded into the StreamingClient of the Streaming Library. To enhance flexibility and maintainability, we should add a GET endpoint in the POP API that returns the Kafka connection details in JSON format.

This change will also require updates in the POP Python Library to include a method for accessing the new endpoint.
Proposed API Endpoint

    Endpoint: /kafka/connection-details
    Method: GET
    Response Example:

    {
        "kafka_host": "155.101.6.194",
        "kafka_port": 9092,
        "kafka_prefix": "data_stream_",
        "max_streams": 10
    }

Required Changes

    POP API:
        Add the /kafka/connection-details endpoint to return the Kafka connection details. (Raul)

    POP Python Library:
        Add a new method get_kafka_details() to fetch the Kafka connection details from the POP API. (Raul)

    Streaming Library:
        Update the StreamingClient class to dynamically fetch Kafka connection details via the new endpoint using the POP Python Library. (Andreu)

**Comment by rbardaji** [comment]
Hi @Andreufb,

I’m not sure I understand how this differs from /search. The connection details are located in the metadata of a Kafka object, right? I believe the details you mentioned can be found using /search. Am I correct or you are looking for other "connection details"?

**Comment by rbardaji** [comment]
Done.
