### ISSUE TITLE
Improvement Suggestion: Filter Search Results by Matching All Keywords in API

### ISSUE THREAD

**Issue by Andreufb** [sci-ndp/pop#8]
The current implementation of the search_datasets functionality returns results where partial matches for any of the keywords are present in the data objects. However, this behavior can lead to results that do not strictly match all the specified keywords. This inconsistency can result in unwanted data being included in the results.

To address this issue in my library (streaming-py), I implemented a helper function that ensures only streams containing all keywords in their string representation are returned. While this works as a temporary fix, I believe this functionality could be better handled at the API level to streamline the experience and reduce overhead for clients using the API.

Proposed Solution:
Introduce a filtering mechanism in the API that checks if all specified keywords are present in the relevant fields of the data objects returned by CKAN,:

def filter_streams_with_all_keywords(CKAN_response, terms):
    result = []
    for stream in CKAN_response:
        stream_str = str(stream).lower()  # Convert the entire stream to a lowercase string for case-insensitive matching
        if all(term.lower() in stream_str for term in terms):
            result.append(stream)
    return result

**Comment by saleemalharir1** [comment]
@Andreufb you can extend the search function with your own implementation or modification of the search 
your library can do the extended search while keeping the pop as it is  let me know if i am misunderstanding this or we need to get on a quick call to clarify this

**Comment by Andreufb** [comment]
Yes that's what I did but I think that we need this improvemnt in the API also. I already have some code to improve the search in my streaming API that taggle this issue of the CKAN search, we can meet to discuss it. For me it doesn't have an impact as I alrerady have the code on my extensions (library and API) but I think that it's a needed update.
